let counter = 0

console.log(counter)
console.log(counter + 1)
console.log(counter + 2)
console.log(counter + 3)
console.log(counter + 4)
console.log(counter + 5)
console.log(counter + 6)
console.log(counter + 7)
console.log(counter + 8)
console.log(counter + 9)
console.log(counter + 10)
console.log(counter + 11)
console.log(counter + 12)
console.log(counter + 13)
console.log(counter + 14)
console.log(counter + 15)
console.log(counter + 16)
console.log(counter + 17)
console.log(counter + 18)
console.log(counter + 19)
console.log(counter + 20)